# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keck/mast_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keck/mast_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keck/mast_project/CMakeFiles /home/keck/mast_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keck/mast_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mast_project

# Build rule for target.
mast_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mast_project
.PHONY : mast_project

# fast build rule for target.
mast_project/fast:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/build
.PHONY : mast_project/fast

src/core/Corresponder.o: src/core/Corresponder.cpp.o
.PHONY : src/core/Corresponder.o

# target to build an object file
src/core/Corresponder.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Corresponder.cpp.o
.PHONY : src/core/Corresponder.cpp.o

src/core/Corresponder.i: src/core/Corresponder.cpp.i
.PHONY : src/core/Corresponder.i

# target to preprocess a source file
src/core/Corresponder.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Corresponder.cpp.i
.PHONY : src/core/Corresponder.cpp.i

src/core/Corresponder.s: src/core/Corresponder.cpp.s
.PHONY : src/core/Corresponder.s

# target to generate assembly for a file
src/core/Corresponder.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Corresponder.cpp.s
.PHONY : src/core/Corresponder.cpp.s

src/core/Frame_Classes.o: src/core/Frame_Classes.cpp.o
.PHONY : src/core/Frame_Classes.o

# target to build an object file
src/core/Frame_Classes.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Frame_Classes.cpp.o
.PHONY : src/core/Frame_Classes.cpp.o

src/core/Frame_Classes.i: src/core/Frame_Classes.cpp.i
.PHONY : src/core/Frame_Classes.i

# target to preprocess a source file
src/core/Frame_Classes.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Frame_Classes.cpp.i
.PHONY : src/core/Frame_Classes.cpp.i

src/core/Frame_Classes.s: src/core/Frame_Classes.cpp.s
.PHONY : src/core/Frame_Classes.s

# target to generate assembly for a file
src/core/Frame_Classes.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Frame_Classes.cpp.s
.PHONY : src/core/Frame_Classes.cpp.s

src/core/ImageSim.o: src/core/ImageSim.cpp.o
.PHONY : src/core/ImageSim.o

# target to build an object file
src/core/ImageSim.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/ImageSim.cpp.o
.PHONY : src/core/ImageSim.cpp.o

src/core/ImageSim.i: src/core/ImageSim.cpp.i
.PHONY : src/core/ImageSim.i

# target to preprocess a source file
src/core/ImageSim.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/ImageSim.cpp.i
.PHONY : src/core/ImageSim.cpp.i

src/core/ImageSim.s: src/core/ImageSim.cpp.s
.PHONY : src/core/ImageSim.s

# target to generate assembly for a file
src/core/ImageSim.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/ImageSim.cpp.s
.PHONY : src/core/ImageSim.cpp.s

src/core/Initilizer.o: src/core/Initilizer.cpp.o
.PHONY : src/core/Initilizer.o

# target to build an object file
src/core/Initilizer.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Initilizer.cpp.o
.PHONY : src/core/Initilizer.cpp.o

src/core/Initilizer.i: src/core/Initilizer.cpp.i
.PHONY : src/core/Initilizer.i

# target to preprocess a source file
src/core/Initilizer.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Initilizer.cpp.i
.PHONY : src/core/Initilizer.cpp.i

src/core/Initilizer.s: src/core/Initilizer.cpp.s
.PHONY : src/core/Initilizer.s

# target to generate assembly for a file
src/core/Initilizer.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/Initilizer.cpp.s
.PHONY : src/core/Initilizer.cpp.s

src/core/SFMgraph.o: src/core/SFMgraph.cpp.o
.PHONY : src/core/SFMgraph.o

# target to build an object file
src/core/SFMgraph.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/SFMgraph.cpp.o
.PHONY : src/core/SFMgraph.cpp.o

src/core/SFMgraph.i: src/core/SFMgraph.cpp.i
.PHONY : src/core/SFMgraph.i

# target to preprocess a source file
src/core/SFMgraph.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/SFMgraph.cpp.i
.PHONY : src/core/SFMgraph.cpp.i

src/core/SFMgraph.s: src/core/SFMgraph.cpp.s
.PHONY : src/core/SFMgraph.s

# target to generate assembly for a file
src/core/SFMgraph.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/core/SFMgraph.cpp.s
.PHONY : src/core/SFMgraph.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/types/JPL7.o: src/types/JPL7.cpp.o
.PHONY : src/types/JPL7.o

# target to build an object file
src/types/JPL7.cpp.o:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/types/JPL7.cpp.o
.PHONY : src/types/JPL7.cpp.o

src/types/JPL7.i: src/types/JPL7.cpp.i
.PHONY : src/types/JPL7.i

# target to preprocess a source file
src/types/JPL7.cpp.i:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/types/JPL7.cpp.i
.PHONY : src/types/JPL7.cpp.i

src/types/JPL7.s: src/types/JPL7.cpp.s
.PHONY : src/types/JPL7.s

# target to generate assembly for a file
src/types/JPL7.cpp.s:
	$(MAKE) -f CMakeFiles/mast_project.dir/build.make CMakeFiles/mast_project.dir/src/types/JPL7.cpp.s
.PHONY : src/types/JPL7.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mast_project"
	@echo "... rebuild_cache"
	@echo "... src/core/Corresponder.o"
	@echo "... src/core/Corresponder.i"
	@echo "... src/core/Corresponder.s"
	@echo "... src/core/Frame_Classes.o"
	@echo "... src/core/Frame_Classes.i"
	@echo "... src/core/Frame_Classes.s"
	@echo "... src/core/ImageSim.o"
	@echo "... src/core/ImageSim.i"
	@echo "... src/core/ImageSim.s"
	@echo "... src/core/Initilizer.o"
	@echo "... src/core/Initilizer.i"
	@echo "... src/core/Initilizer.s"
	@echo "... src/core/SFMgraph.o"
	@echo "... src/core/SFMgraph.i"
	@echo "... src/core/SFMgraph.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/types/JPL7.o"
	@echo "... src/types/JPL7.i"
	@echo "... src/types/JPL7.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

